package com.example.hybrid_ai_app.core.data.local

import androidx.room.Database
import androidx.room.RoomDatabase
import androidx.room.TypeConverters
import com.example.hybrid_ai_app.core.data.local.converter.WorkoutLogConverters
import com.example.hybrid_ai_app.core.data.local.converter.WorkoutPlanConverters
import com.example.hybrid_ai_app.core.data.local.dao.ProgressDao
import com.example.hybrid_ai_app.core.data.local.dao.WorkoutPlanDao
import com.example.hybrid_ai_app.core.data.local.entity.UserProgressEntity
import com.example.hybrid_ai_app.core.data.local.entity.WorkoutLogEntity
import com.example.hybrid_ai_app.core.data.local.entity.WorkoutPlanEntity

@Database(
    entities = [
        WorkoutPlanEntity::class,
        UserProgressEntity::class,
        WorkoutLogEntity::class
    ],
    version = 3,
    exportSchema = false
)
@TypeConverters(WorkoutPlanConverters::class, WorkoutLogConverters::class)
abstract class AppDatabase : RoomDatabase() {

    // Concrete implementations will be generated by Room via KSP
    abstract fun workoutPlanDao(): WorkoutPlanDao

    abstract fun progressDao(): ProgressDao // Exposed DAO for tracking capabilities
}